name: Build and Push Nix Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: ZeroTier
      #   uses: zerotier/github-action@v1.0.1
      #   with:
      #     network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
      #     auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      #

      - name: Setup Nix
        uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.19.3/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable nix cache action
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Docker image with Nix
        run: nix run .#container.copyToDockerDaemon

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/pep-container-${{ matrix.platform }}:latest
          docker tag $(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1) $IMAGE_ID
          docker push $IMAGE_ID

