name: "Test"
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v17
    - run: nix develop --experimental-features 'nix-command flakes' --command ci-test
